version: '3.8'

services:

  go-cart-api:
    container_name: go-cart-api
    image: christianprzybulinski/go-cart-api
    build: 
      context: .
      dockerfile: docker/go-cart-api
    env_file: .env
    networks:
      - default
    ports:
    - "${API_PORT}:${API_PORT}"
    restart: on-failure
    volumes:
      - .:${APP_PATH}/go-cart-api

  discount-service:
    container_name: discount-service
    image: hashorg/hash-mock-discount-service
    build:
      context: .
      dockerfile: docker/discount-service
    networks:
      - default
    ports:
    - "${DISCOUNT_SERVICE_PORT}:${DISCOUNT_SERVICE_PORT}"
    restart: on-failure
    volumes:
      - .:${APP_PATH}/discount-service